/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef PROFILETABLE_INTERFACE_H
#define PROFILETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "profileTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _profileTable_initialize_interface(profileTable_registration * user_ctx,
                                    u_long flags);
void _profileTable_shutdown_interface(profileTable_registration * user_ctx);

profileTable_registration *
profileTable_registration_get( void );

profileTable_registration *
profileTable_registration_set( profileTable_registration * newreg );

netsnmp_container *profileTable_container_get( void );
int profileTable_container_size( void );

u_int profileTable_dirty_get( void );
void profileTable_dirty_set( u_int status );

    profileTable_rowreq_ctx * profileTable_allocate_rowreq_ctx(void *);
void profileTable_release_rowreq_ctx(profileTable_rowreq_ctx *rowreq_ctx);

int profileTable_index_to_oid(netsnmp_index *oid_idx,
                            profileTable_mib_index *mib_idx);
int profileTable_index_from_oid(netsnmp_index *oid_idx,
                              profileTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void profileTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* PROFILETABLE_INTERFACE_H */
/** @} */
