/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef PROFILETABLE_DATA_SET_H
#define PROFILETABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table profileTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::profileTable is subid 8 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.8, length: 9
*/


int profileTable_undo_setup( profileTable_rowreq_ctx *rowreq_ctx);
int profileTable_undo_cleanup( profileTable_rowreq_ctx *rowreq_ctx);
int profileTable_undo( profileTable_rowreq_ctx *rowreq_ctx);
int profileTable_commit( profileTable_rowreq_ctx *rowreq_ctx);
int profileTable_undo_commit( profileTable_rowreq_ctx *rowreq_ctx);


int proIndex_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proIndex_val);
int proIndex_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proIndex_set( profileTable_rowreq_ctx *rowreq_ctx, long proIndex_val );
int proIndex_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proBase_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proBase_val);
int proBase_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proBase_set( profileTable_rowreq_ctx *rowreq_ctx, long proBase_val );
int proBase_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proMacLimit_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proMacLimit_val);
int proMacLimit_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proMacLimit_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proMacLimit_val );
int proMacLimit_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCableUplinkRate_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proCableUplinkRate_val);
int proCableUplinkRate_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCableUplinkRate_set( profileTable_rowreq_ctx *rowreq_ctx, long proCableUplinkRate_val );
int proCableUplinkRate_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCableDownlinkRate_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proCableDownlinkRate_val);
int proCableDownlinkRate_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCableDownlinkRate_set( profileTable_rowreq_ctx *rowreq_ctx, long proCableDownlinkRate_val );
int proCableDownlinkRate_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proLocalAgingTime_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proLocalAgingTime_val);
int proLocalAgingTime_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proLocalAgingTime_set( profileTable_rowreq_ctx *rowreq_ctx, long proLocalAgingTime_val );
int proLocalAgingTime_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proRemoteAgingTime_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proRemoteAgingTime_val);
int proRemoteAgingTime_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proRemoteAgingTime_set( profileTable_rowreq_ctx *rowreq_ctx, long proRemoteAgingTime_val );
int proRemoteAgingTime_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proIgmpPri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proIgmpPri_val);
int proIgmpPri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proIgmpPri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proIgmpPri_val );
int proIgmpPri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proUnicastPri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proUnicastPri_val);
int proUnicastPri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proUnicastPri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proUnicastPri_val );
int proUnicastPri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proAvsPri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proAvsPri_val);
int proAvsPri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proAvsPri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proAvsPri_val );
int proAvsPri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proMcastPri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proMcastPri_val);
int proMcastPri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proMcastPri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proMcastPri_val );
int proMcastPri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTbaPriSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTbaPriSts_val);
int proTbaPriSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTbaPriSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTbaPriSts_val );
int proTbaPriSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCosPriSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCosPriSts_val);
int proCosPriSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCosPriSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCosPriSts_val );
int proCosPriSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos0pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos0pri_val);
int proCos0pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos0pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos0pri_val );
int proCos0pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos1pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos1pri_val);
int proCos1pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos1pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos1pri_val );
int proCos1pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos2pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos2pri_val);
int proCos2pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos2pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos2pri_val );
int proCos2pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos3pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos3pri_val);
int proCos3pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos3pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos3pri_val );
int proCos3pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos4pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos4pri_val);
int proCos4pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos4pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos4pri_val );
int proCos4pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos5pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos5pri_val);
int proCos5pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos5pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos5pri_val );
int proCos5pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos6pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos6pri_val);
int proCos6pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos6pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos6pri_val );
int proCos6pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCos7pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos7pri_val);
int proCos7pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCos7pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCos7pri_val );
int proCos7pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTosPriSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTosPriSts_val);
int proTosPriSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTosPriSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTosPriSts_val );
int proTosPriSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos0pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos0pri_val);
int proTos0pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos0pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos0pri_val );
int proTos0pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos1pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos1pri_val);
int proTos1pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos1pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos1pri_val );
int proTos1pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos2pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos2pri_val);
int proTos2pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos2pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos2pri_val );
int proTos2pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos3pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos3pri_val);
int proTos3pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos3pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos3pri_val );
int proTos3pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos4pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos4pri_val);
int proTos4pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos4pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos4pri_val );
int proTos4pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos5pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos5pri_val);
int proTos5pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos5pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos5pri_val );
int proTos5pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos6pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos6pri_val);
int proTos6pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos6pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos6pri_val );
int proTos6pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTos7pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos7pri_val);
int proTos7pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTos7pri_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTos7pri_val );
int proTos7pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proSfbSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfbSts_val);
int proSfbSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proSfbSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfbSts_val );
int proSfbSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proSfuSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfuSts_val);
int proSfuSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proSfuSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfuSts_val );
int proSfuSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proSfmSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfmSts_val);
int proSfmSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proSfmSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfmSts_val );
int proSfmSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proSfRate_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfRate_val);
int proSfRate_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proSfRate_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proSfRate_val );
int proSfRate_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proVlanStatus_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proVlanStatus_val);
int proVlanStatus_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proVlanStatus_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proVlanStatus_val );
int proVlanStatus_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth1vid_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth1vid_val);
int proEth1vid_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth1vid_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth1vid_val );
int proEth1vid_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth2vid_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth2vid_val);
int proEth2vid_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth2vid_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth2vid_val );
int proEth2vid_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth3vid_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth3vid_val);
int proEth3vid_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth3vid_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth3vid_val );
int proEth3vid_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth4vid_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth4vid_val);
int proEth4vid_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth4vid_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth4vid_val );
int proEth4vid_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proPortPriSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proPortPriSts_val);
int proPortPriSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proPortPriSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proPortPriSts_val );
int proPortPriSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth1pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth1pri_val);
int proEth1pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth1pri_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth1pri_val );
int proEth1pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth2pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth2pri_val);
int proEth2pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth2pri_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth2pri_val );
int proEth2pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth3pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth3pri_val);
int proEth3pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth3pri_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth3pri_val );
int proEth3pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth4pri_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth4pri_val);
int proEth4pri_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth4pri_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth4pri_val );
int proEth4pri_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proRxLimitSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proRxLimitSts_val);
int proRxLimitSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proRxLimitSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proRxLimitSts_val );
int proRxLimitSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCpuPortRxRate_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proCpuPortRxRate_val);
int proCpuPortRxRate_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCpuPortRxRate_set( profileTable_rowreq_ctx *rowreq_ctx, long proCpuPortRxRate_val );
int proCpuPortRxRate_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth1rx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth1rx_val);
int proEth1rx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth1rx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth1rx_val );
int proEth1rx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth2rx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth2rx_val);
int proEth2rx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth2rx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth2rx_val );
int proEth2rx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth3rx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth3rx_val);
int proEth3rx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth3rx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth3rx_val );
int proEth3rx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth4rx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth4rx_val);
int proEth4rx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth4rx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth4rx_val );
int proEth4rx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proTxLimitSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proTxLimitSts_val);
int proTxLimitSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proTxLimitSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proTxLimitSts_val );
int proTxLimitSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCpuPortTxRate_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proCpuPortTxRate_val);
int proCpuPortTxRate_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCpuPortTxRate_set( profileTable_rowreq_ctx *rowreq_ctx, long proCpuPortTxRate_val );
int proCpuPortTxRate_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth1tx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth1tx_val);
int proEth1tx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth1tx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth1tx_val );
int proEth1tx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth2tx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth2tx_val);
int proEth2tx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth2tx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth2tx_val );
int proEth2tx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth3tx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth3tx_val);
int proEth3tx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth3tx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth3tx_val );
int proEth3tx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth4tx_check_value( profileTable_rowreq_ctx *rowreq_ctx, long proEth4tx_val);
int proEth4tx_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth4tx_set( profileTable_rowreq_ctx *rowreq_ctx, long proEth4tx_val );
int proEth4tx_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proPsctlSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proPsctlSts_val);
int proPsctlSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proPsctlSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proPsctlSts_val );
int proPsctlSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCpuPortSts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCpuPortSts_val);
int proCpuPortSts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCpuPortSts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCpuPortSts_val );
int proCpuPortSts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth1sts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth1sts_val);
int proEth1sts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth1sts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth1sts_val );
int proEth1sts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth2sts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth2sts_val);
int proEth2sts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth2sts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth2sts_val );
int proEth2sts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth3sts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth3sts_val);
int proEth3sts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth3sts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth3sts_val );
int proEth3sts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proEth4sts_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth4sts_val);
int proEth4sts_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proEth4sts_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proEth4sts_val );
int proEth4sts_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proCommit_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proCommit_val);
int proCommit_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proCommit_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proCommit_val );
int proCommit_undo( profileTable_rowreq_ctx *rowreq_ctx );

int proRowStatus_check_value( profileTable_rowreq_ctx *rowreq_ctx, u_long proRowStatus_val);
int proRowStatus_undo_setup( profileTable_rowreq_ctx *rowreq_ctx );
int proRowStatus_set( profileTable_rowreq_ctx *rowreq_ctx, u_long proRowStatus_val );
int proRowStatus_undo( profileTable_rowreq_ctx *rowreq_ctx );


int profileTable_check_dependencies(profileTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* PROFILETABLE_DATA_SET_H */
