/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-enums.m2c 12526 2005-07-15 22:41:16Z rstory $
 *
 * $Id:$
 */
#ifndef CLTPROTABLE_ENUMS_H
#define CLTPROTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table cltproTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * cltproMacLimit (HostsLimitingValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef HOSTSLIMITINGVALUE_ENUMS
#define HOSTSLIMITINGVALUE_ENUMS

#define HOSTSLIMITINGVALUE_HOSTS_LIMITING_DISABLED  0 
#define HOSTSLIMITINGVALUE_ONE_HOST  1 
#define HOSTSLIMITINGVALUE_TWO_HOSTS  2 
#define HOSTSLIMITINGVALUE_THREE_HOSTS  3 
#define HOSTSLIMITINGVALUE_FOUR_HOSTS  4 
#define HOSTSLIMITINGVALUE_FIVE_HOSTS  5 
#define HOSTSLIMITINGVALUE_SIX_HOSTS  6 
#define HOSTSLIMITINGVALUE_SEVEN_HOSTS  7 
#define HOSTSLIMITINGVALUE_EIGHT_HOSTS  8 
#define HOSTSLIMITINGVALUE_NULL_HOSTS  65 

#endif /* HOSTSLIMITINGVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproIgmpPri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproUnicastPri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproAvsPri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproMcastPri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTbaPriSts (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCosPriSts (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos0pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos1pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos2pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos3pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos4pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos5pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos6pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCos7pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTosPriSts (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos0pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos1pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos2pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos3pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos4pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos5pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos6pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproTos7pri (PriQueueValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef PRIQUEUEVALUE_ENUMS
#define PRIQUEUEVALUE_ENUMS

#define PRIQUEUEVALUE_CAP0  0 
#define PRIQUEUEVALUE_CAP1  1 
#define PRIQUEUEVALUE_CAP2  2 
#define PRIQUEUEVALUE_CAP3  3 

#endif /* PRIQUEUEVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproCommit (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * cltproRowStatus (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* CLTPROTABLE_ENUMS_H */
