/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file cltproTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CLTPROTABLE_DATA_GET_H
#define CLTPROTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cltproTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cltproTable is subid 10 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.10, length: 9
*/
    /*
     * indexes
     */

    int cltproIndex_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproIndex_val_ptr );
    int cltproBase_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproBase_val_ptr );
    int cltproMacLimit_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproMacLimit_val_ptr );
    int cltproCuRate_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproCuRate_val_ptr );
    int cltproCdRate_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproCdRate_val_ptr );
    int cltproLoagTime_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproLoagTime_val_ptr );
    int cltproReagTime_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproReagTime_val_ptr );
    int cltproIgmpPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproIgmpPri_val_ptr );
    int cltproUnicastPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproUnicastPri_val_ptr );
    int cltproAvsPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproAvsPri_val_ptr );
    int cltproMcastPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproMcastPri_val_ptr );
    int cltproTbaPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTbaPriSts_val_ptr );
    int cltproCosPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCosPriSts_val_ptr );
    int cltproCos0pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos0pri_val_ptr );
    int cltproCos1pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos1pri_val_ptr );
    int cltproCos2pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos2pri_val_ptr );
    int cltproCos3pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos3pri_val_ptr );
    int cltproCos4pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos4pri_val_ptr );
    int cltproCos5pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos5pri_val_ptr );
    int cltproCos6pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos6pri_val_ptr );
    int cltproCos7pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos7pri_val_ptr );
    int cltproTosPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTosPriSts_val_ptr );
    int cltproTos0pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos0pri_val_ptr );
    int cltproTos1pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos1pri_val_ptr );
    int cltproTos2pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos2pri_val_ptr );
    int cltproTos3pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos3pri_val_ptr );
    int cltproTos4pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos4pri_val_ptr );
    int cltproTos5pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos5pri_val_ptr );
    int cltproTos6pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos6pri_val_ptr );
    int cltproTos7pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos7pri_val_ptr );
    int cltproCommit_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCommit_val_ptr );
    int cltproRowStatus_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproRowStatus_val_ptr );


int cltproTable_indexes_set_tbl_idx(cltproTable_mib_index *tbl_idx, long cltproTid_val);
int cltproTable_indexes_set(cltproTable_rowreq_ctx *rowreq_ctx, long cltproTid_val);




#ifdef __cplusplus
}
#endif

#endif /* CLTPROTABLE_DATA_GET_H */
/** @} */
