/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CLTPROTABLE_INTERFACE_H
#define CLTPROTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "cltproTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _cltproTable_initialize_interface(cltproTable_registration * user_ctx,
                                    u_long flags);
void _cltproTable_shutdown_interface(cltproTable_registration * user_ctx);

cltproTable_registration *
cltproTable_registration_get( void );

cltproTable_registration *
cltproTable_registration_set( cltproTable_registration * newreg );

netsnmp_container *cltproTable_container_get( void );
int cltproTable_container_size( void );

u_int cltproTable_dirty_get( void );
void cltproTable_dirty_set( u_int status );

    cltproTable_rowreq_ctx * cltproTable_allocate_rowreq_ctx(void *);
void cltproTable_release_rowreq_ctx(cltproTable_rowreq_ctx *rowreq_ctx);

int cltproTable_index_to_oid(netsnmp_index *oid_idx,
                            cltproTable_mib_index *mib_idx);
int cltproTable_index_from_oid(netsnmp_index *oid_idx,
                              cltproTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void cltproTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CLTPROTABLE_INTERFACE_H */
/** @} */
