/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cltproTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement cltproTable get routines.
 * TODO:240:M: Implement cltproTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cltproTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cltproTable is subid 10 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.10, length: 9
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement cltproTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param cltproTid_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
cltproTable_indexes_set_tbl_idx(cltproTable_mib_index *tbl_idx, long cltproTid_val)
{
    DEBUGMSGTL(("verbose:cltproTable:cltproTable_indexes_set_tbl_idx","called\n"));

    /* cltproTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->cltproTid = cltproTid_val;
    

    return MFD_SUCCESS;
} /* cltproTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
cltproTable_indexes_set(cltproTable_rowreq_ctx *rowreq_ctx, long cltproTid_val)
{
    DEBUGMSGTL(("verbose:cltproTable:cltproTable_indexes_set","called\n"));

    if(MFD_SUCCESS != cltproTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , cltproTid_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != cltproTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* cltproTable_indexes_set */


/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproIndex
 * cltproIndex is subid 2 of cltproEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.10.1.2
 * Description:
the index of clt profile entry in databases.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 4;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproIndex data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproIndex_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproIndex_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproIndex_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproIndex_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproIndex_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproIndex data.
 * copy (* cltproIndex_val_ptr ) from rowreq_ctx->data
 */
    (* cltproIndex_val_ptr ) = rowreq_ctx->data.cltproIndex;

    return MFD_SUCCESS;
} /* cltproIndex_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproBase
 * cltproBase is subid 3 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.3
 * Description:
atheros eoc pib index.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  1 - 32;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproBase data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproBase_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproBase_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproBase_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproBase_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproBase_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproBase data.
 * copy (* cltproBase_val_ptr ) from rowreq_ctx->data
 */
    (* cltproBase_val_ptr ) = rowreq_ctx->data.cltproBase;

    return MFD_SUCCESS;
} /* cltproBase_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproMacLimit
 * cltproMacLimit is subid 4 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.4
 * Description:
EoC bridged hosts limiting.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 8/16. Values:  hosts_limiting_disabled(0), one_host(1), two_hosts(2), three_hosts(3), four_hosts(4), five_hosts(5), six_hosts(6), seven_hosts(7), eight_hosts(8), null_hosts(65)
 *
 * Its syntax is HostsLimitingValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproMacLimit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproMacLimit_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproMacLimit_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproMacLimit_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproMacLimit_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproMacLimit_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproMacLimit data.
 * copy (* cltproMacLimit_val_ptr ) from rowreq_ctx->data
 */
    (* cltproMacLimit_val_ptr ) = rowreq_ctx->data.cltproMacLimit;

    return MFD_SUCCESS;
} /* cltproMacLimit_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCuRate
 * cltproCuRate is subid 5 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.5
 * Description:
Cable uplink rate limiting in kbps.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproCuRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCuRate_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCuRate_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproCuRate_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCuRate_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCuRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCuRate data.
 * copy (* cltproCuRate_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCuRate_val_ptr ) = rowreq_ctx->data.cltproCuRate;

    return MFD_SUCCESS;
} /* cltproCuRate_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCdRate
 * cltproCdRate is subid 6 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.6
 * Description:
Cable downlink rate limiting in kbps.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproCdRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCdRate_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCdRate_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproCdRate_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCdRate_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCdRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCdRate data.
 * copy (* cltproCdRate_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCdRate_val_ptr ) = rowreq_ctx->data.cltproCdRate;

    return MFD_SUCCESS;
} /* cltproCdRate_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproLoagTime
 * cltproLoagTime is subid 7 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.7
 * Description:
Local bridge aging time in minutes.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproLoagTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproLoagTime_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproLoagTime_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproLoagTime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproLoagTime_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproLoagTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproLoagTime data.
 * copy (* cltproLoagTime_val_ptr ) from rowreq_ctx->data
 */
    (* cltproLoagTime_val_ptr ) = rowreq_ctx->data.cltproLoagTime;

    return MFD_SUCCESS;
} /* cltproLoagTime_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproReagTime
 * cltproReagTime is subid 8 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.8
 * Description:
Remote devie bridge table aging time in minutes.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltproReagTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproReagTime_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproReagTime_get( cltproTable_rowreq_ctx *rowreq_ctx, long * cltproReagTime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproReagTime_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproReagTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproReagTime data.
 * copy (* cltproReagTime_val_ptr ) from rowreq_ctx->data
 */
    (* cltproReagTime_val_ptr ) = rowreq_ctx->data.cltproReagTime;

    return MFD_SUCCESS;
} /* cltproReagTime_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproIgmpPri
 * cltproIgmpPri is subid 9 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.9
 * Description:
IGMP Priority CAP value.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproIgmpPri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproIgmpPri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproIgmpPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproIgmpPri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproIgmpPri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproIgmpPri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproIgmpPri data.
 * copy (* cltproIgmpPri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproIgmpPri_val_ptr ) = rowreq_ctx->data.cltproIgmpPri;

    return MFD_SUCCESS;
} /* cltproIgmpPri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproUnicastPri
 * cltproUnicastPri is subid 10 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.10
 * Description:
Unicast Priority CAP value.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproUnicastPri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproUnicastPri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproUnicastPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproUnicastPri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproUnicastPri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproUnicastPri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproUnicastPri data.
 * copy (* cltproUnicastPri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproUnicastPri_val_ptr ) = rowreq_ctx->data.cltproUnicastPri;

    return MFD_SUCCESS;
} /* cltproUnicastPri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproAvsPri
 * cltproAvsPri is subid 11 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.11
 * Description:
AV Stream Priority CAP value.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproAvsPri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproAvsPri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproAvsPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproAvsPri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproAvsPri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproAvsPri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproAvsPri data.
 * copy (* cltproAvsPri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproAvsPri_val_ptr ) = rowreq_ctx->data.cltproAvsPri;

    return MFD_SUCCESS;
} /* cltproAvsPri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproMcastPri
 * cltproMcastPri is subid 12 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.12
 * Description:
Multicast Priority CAP value.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproMcastPri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproMcastPri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproMcastPri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproMcastPri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproMcastPri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproMcastPri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproMcastPri data.
 * copy (* cltproMcastPri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproMcastPri_val_ptr ) = rowreq_ctx->data.cltproMcastPri;

    return MFD_SUCCESS;
} /* cltproMcastPri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTbaPriSts
 * cltproTbaPriSts is subid 13 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.13
 * Description:
TX buffer based on priority status.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTbaPriSts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTbaPriSts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTbaPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTbaPriSts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTbaPriSts_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTbaPriSts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTbaPriSts data.
 * copy (* cltproTbaPriSts_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTbaPriSts_val_ptr ) = rowreq_ctx->data.cltproTbaPriSts;

    return MFD_SUCCESS;
} /* cltproTbaPriSts_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCosPriSts
 * cltproCosPriSts is subid 14 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.14
 * Description:
Map VLAN to Priority CAP.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCosPriSts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCosPriSts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCosPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCosPriSts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCosPriSts_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCosPriSts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCosPriSts data.
 * copy (* cltproCosPriSts_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCosPriSts_val_ptr ) = rowreq_ctx->data.cltproCosPriSts;

    return MFD_SUCCESS;
} /* cltproCosPriSts_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos0pri
 * cltproCos0pri is subid 15 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.15
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos0pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos0pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos0pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos0pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos0pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos0pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos0pri data.
 * copy (* cltproCos0pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos0pri_val_ptr ) = rowreq_ctx->data.cltproCos0pri;

    return MFD_SUCCESS;
} /* cltproCos0pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos1pri
 * cltproCos1pri is subid 16 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.16
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos1pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos1pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos1pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos1pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos1pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos1pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos1pri data.
 * copy (* cltproCos1pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos1pri_val_ptr ) = rowreq_ctx->data.cltproCos1pri;

    return MFD_SUCCESS;
} /* cltproCos1pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos2pri
 * cltproCos2pri is subid 17 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.17
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos2pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos2pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos2pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos2pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos2pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos2pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos2pri data.
 * copy (* cltproCos2pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos2pri_val_ptr ) = rowreq_ctx->data.cltproCos2pri;

    return MFD_SUCCESS;
} /* cltproCos2pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos3pri
 * cltproCos3pri is subid 18 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.18
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos3pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos3pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos3pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos3pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos3pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos3pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos3pri data.
 * copy (* cltproCos3pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos3pri_val_ptr ) = rowreq_ctx->data.cltproCos3pri;

    return MFD_SUCCESS;
} /* cltproCos3pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos4pri
 * cltproCos4pri is subid 19 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.19
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos4pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos4pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos4pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos4pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos4pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos4pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos4pri data.
 * copy (* cltproCos4pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos4pri_val_ptr ) = rowreq_ctx->data.cltproCos4pri;

    return MFD_SUCCESS;
} /* cltproCos4pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos5pri
 * cltproCos5pri is subid 20 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.20
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos5pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos5pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos5pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos5pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos5pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos5pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos5pri data.
 * copy (* cltproCos5pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos5pri_val_ptr ) = rowreq_ctx->data.cltproCos5pri;

    return MFD_SUCCESS;
} /* cltproCos5pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos6pri
 * cltproCos6pri is subid 21 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.21
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos6pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos6pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos6pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos6pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos6pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos6pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos6pri data.
 * copy (* cltproCos6pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos6pri_val_ptr ) = rowreq_ctx->data.cltproCos6pri;

    return MFD_SUCCESS;
} /* cltproCos6pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCos7pri
 * cltproCos7pri is subid 22 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.22
 * Description:
VLAN priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCos7pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCos7pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCos7pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCos7pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCos7pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCos7pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCos7pri data.
 * copy (* cltproCos7pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCos7pri_val_ptr ) = rowreq_ctx->data.cltproCos7pri;

    return MFD_SUCCESS;
} /* cltproCos7pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTosPriSts
 * cltproTosPriSts is subid 23 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.23
 * Description:
Map TOS to Priority CAP.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTosPriSts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTosPriSts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTosPriSts_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTosPriSts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTosPriSts_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTosPriSts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTosPriSts data.
 * copy (* cltproTosPriSts_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTosPriSts_val_ptr ) = rowreq_ctx->data.cltproTosPriSts;

    return MFD_SUCCESS;
} /* cltproTosPriSts_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos0pri
 * cltproTos0pri is subid 24 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.24
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos0pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos0pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos0pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos0pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos0pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos0pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos0pri data.
 * copy (* cltproTos0pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos0pri_val_ptr ) = rowreq_ctx->data.cltproTos0pri;

    return MFD_SUCCESS;
} /* cltproTos0pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos1pri
 * cltproTos1pri is subid 25 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.25
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos1pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos1pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos1pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos1pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos1pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos1pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos1pri data.
 * copy (* cltproTos1pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos1pri_val_ptr ) = rowreq_ctx->data.cltproTos1pri;

    return MFD_SUCCESS;
} /* cltproTos1pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos2pri
 * cltproTos2pri is subid 26 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.26
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos2pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos2pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos2pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos2pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos2pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos2pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos2pri data.
 * copy (* cltproTos2pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos2pri_val_ptr ) = rowreq_ctx->data.cltproTos2pri;

    return MFD_SUCCESS;
} /* cltproTos2pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos3pri
 * cltproTos3pri is subid 27 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.27
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos3pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos3pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos3pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos3pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos3pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos3pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos3pri data.
 * copy (* cltproTos3pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos3pri_val_ptr ) = rowreq_ctx->data.cltproTos3pri;

    return MFD_SUCCESS;
} /* cltproTos3pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos4pri
 * cltproTos4pri is subid 28 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.28
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos4pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos4pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos4pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos4pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos4pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos4pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos4pri data.
 * copy (* cltproTos4pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos4pri_val_ptr ) = rowreq_ctx->data.cltproTos4pri;

    return MFD_SUCCESS;
} /* cltproTos4pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos5pri
 * cltproTos5pri is subid 29 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.29
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos5pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos5pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos5pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos5pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos5pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos5pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos5pri data.
 * copy (* cltproTos5pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos5pri_val_ptr ) = rowreq_ctx->data.cltproTos5pri;

    return MFD_SUCCESS;
} /* cltproTos5pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos6pri
 * cltproTos6pri is subid 30 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.30
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos6pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos6pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos6pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos6pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos6pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos6pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos6pri data.
 * copy (* cltproTos6pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos6pri_val_ptr ) = rowreq_ctx->data.cltproTos6pri;

    return MFD_SUCCESS;
} /* cltproTos6pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproTos7pri
 * cltproTos7pri is subid 31 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.31
 * Description:
TOS priority mappings.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cap0(0), cap1(1), cap2(2), cap3(3)
 *
 * Its syntax is PriQueueValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproTos7pri data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproTos7pri_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproTos7pri_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproTos7pri_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproTos7pri_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproTos7pri_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproTos7pri data.
 * copy (* cltproTos7pri_val_ptr ) from rowreq_ctx->data
 */
    (* cltproTos7pri_val_ptr ) = rowreq_ctx->data.cltproTos7pri;

    return MFD_SUCCESS;
} /* cltproTos7pri_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproCommit
 * cltproCommit is subid 32 of cltproEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.10.1.32
 * Description:
Commit action node for saving current profile settings to databases.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproCommit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproCommit_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproCommit_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproCommit_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproCommit_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproCommit_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproCommit data.
 * copy (* cltproCommit_val_ptr ) from rowreq_ctx->data
 */
    (* cltproCommit_val_ptr ) = rowreq_ctx->data.cltproCommit;

    return MFD_SUCCESS;
} /* cltproCommit_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltproEntry.cltproRowStatus
 * cltproRowStatus is subid 33 of cltproEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.10.1.33
 * Description:
Clt profile entry row status.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltproRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltproRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltproRowStatus_get( cltproTable_rowreq_ctx *rowreq_ctx, u_long * cltproRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltproRowStatus_val_ptr );


    DEBUGMSGTL(("verbose:cltproTable:cltproRowStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltproRowStatus data.
 * copy (* cltproRowStatus_val_ptr ) from rowreq_ctx->data
 */
    (* cltproRowStatus_val_ptr ) = rowreq_ctx->data.cltproRowStatus;

    return MFD_SUCCESS;
} /* cltproRowStatus_get */



/** @} */
