/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file cnuTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CNUTABLE_DATA_GET_H
#define CNUTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cnuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cnuTable is subid 1 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.1, length: 9
*/
    /*
     * indexes
     */

    int cnuIndex_get( cnuTable_rowreq_ctx *rowreq_ctx, long * cnuIndex_val_ptr );
    int cnuModel_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuModel_val_ptr );
    int cnuMacAddress_get( cnuTable_rowreq_ctx *rowreq_ctx, char **cnuMacAddress_val_ptr_ptr, size_t *cnuMacAddress_val_ptr_len_ptr );
    int cnuOnlineStatus_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuOnlineStatus_val_ptr );
    int cnuAuthorized_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuAuthorized_val_ptr );
    int cnuSoftwareVersion_get( cnuTable_rowreq_ctx *rowreq_ctx, char **cnuSoftwareVersion_val_ptr_ptr, size_t *cnuSoftwareVersion_val_ptr_len_ptr );
    int cnuRxRate_get( cnuTable_rowreq_ctx *rowreq_ctx, long * cnuRxRate_val_ptr );
    int cnuTxRate_get( cnuTable_rowreq_ctx *rowreq_ctx, long * cnuTxRate_val_ptr );
    int cnuSnr_get( cnuTable_rowreq_ctx *rowreq_ctx, char **cnuSnr_val_ptr_ptr, size_t *cnuSnr_val_ptr_len_ptr );
    int cnuBpc_get( cnuTable_rowreq_ctx *rowreq_ctx, char **cnuBpc_val_ptr_ptr, size_t *cnuBpc_val_ptr_len_ptr );
    int cnuAttenuation_get( cnuTable_rowreq_ctx *rowreq_ctx, char **cnuAttenuation_val_ptr_ptr, size_t *cnuAttenuation_val_ptr_len_ptr );
    int cnuAction_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuAction_val_ptr );
    int cnuSynchronized_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuSynchronized_val_ptr );
    int cnuRowStatus_get( cnuTable_rowreq_ctx *rowreq_ctx, u_long * cnuRowStatus_val_ptr );


int cnuTable_indexes_set_tbl_idx(cnuTable_mib_index *tbl_idx, long cnuTid_val);
int cnuTable_indexes_set(cnuTable_rowreq_ctx *rowreq_ctx, long cnuTid_val);




#ifdef __cplusplus
}
#endif

#endif /* CNUTABLE_DATA_GET_H */
/** @} */
