/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef CNUTABLE_DATA_SET_H
#define CNUTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cnuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cnuTable is subid 1 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.1, length: 9
*/


int cnuTable_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx);
int cnuTable_undo_cleanup( cnuTable_rowreq_ctx *rowreq_ctx);
int cnuTable_undo( cnuTable_rowreq_ctx *rowreq_ctx);
int cnuTable_commit( cnuTable_rowreq_ctx *rowreq_ctx);
int cnuTable_undo_commit( cnuTable_rowreq_ctx *rowreq_ctx);


int cnuIndex_check_value( cnuTable_rowreq_ctx *rowreq_ctx, long cnuIndex_val);
int cnuIndex_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuIndex_set( cnuTable_rowreq_ctx *rowreq_ctx, long cnuIndex_val );
int cnuIndex_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuModel_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuModel_val);
int cnuModel_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuModel_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuModel_val );
int cnuModel_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuMacAddress_check_value( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuMacAddress_val_ptr,  size_t cnuMacAddress_val_ptr_len);
int cnuMacAddress_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuMacAddress_set( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuMacAddress_val_ptr,  size_t cnuMacAddress_val_ptr_len );
int cnuMacAddress_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuOnlineStatus_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuOnlineStatus_val);
int cnuOnlineStatus_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuOnlineStatus_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuOnlineStatus_val );
int cnuOnlineStatus_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuAuthorized_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAuthorized_val);
int cnuAuthorized_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuAuthorized_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAuthorized_val );
int cnuAuthorized_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuSoftwareVersion_check_value( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuSoftwareVersion_val_ptr,  size_t cnuSoftwareVersion_val_ptr_len);
int cnuSoftwareVersion_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuSoftwareVersion_set( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuSoftwareVersion_val_ptr,  size_t cnuSoftwareVersion_val_ptr_len );
int cnuSoftwareVersion_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuRxRate_check_value( cnuTable_rowreq_ctx *rowreq_ctx, long cnuRxRate_val);
int cnuRxRate_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuRxRate_set( cnuTable_rowreq_ctx *rowreq_ctx, long cnuRxRate_val );
int cnuRxRate_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuTxRate_check_value( cnuTable_rowreq_ctx *rowreq_ctx, long cnuTxRate_val);
int cnuTxRate_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuTxRate_set( cnuTable_rowreq_ctx *rowreq_ctx, long cnuTxRate_val );
int cnuTxRate_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuSnr_check_value( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuSnr_val_ptr,  size_t cnuSnr_val_ptr_len);
int cnuSnr_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuSnr_set( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuSnr_val_ptr,  size_t cnuSnr_val_ptr_len );
int cnuSnr_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuBpc_check_value( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuBpc_val_ptr,  size_t cnuBpc_val_ptr_len);
int cnuBpc_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuBpc_set( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuBpc_val_ptr,  size_t cnuBpc_val_ptr_len );
int cnuBpc_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuAttenuation_check_value( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuAttenuation_val_ptr,  size_t cnuAttenuation_val_ptr_len);
int cnuAttenuation_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuAttenuation_set( cnuTable_rowreq_ctx *rowreq_ctx, char *cnuAttenuation_val_ptr,  size_t cnuAttenuation_val_ptr_len );
int cnuAttenuation_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuAction_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAction_val);
int cnuAction_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuAction_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAction_val );
int cnuAction_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuSynchronized_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuSynchronized_val);
int cnuSynchronized_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuSynchronized_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuSynchronized_val );
int cnuSynchronized_undo( cnuTable_rowreq_ctx *rowreq_ctx );

int cnuRowStatus_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuRowStatus_val);
int cnuRowStatus_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx );
int cnuRowStatus_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuRowStatus_val );
int cnuRowStatus_undo( cnuTable_rowreq_ctx *rowreq_ctx );


int cnuTable_check_dependencies(cnuTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CNUTABLE_DATA_SET_H */
