/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CNUTABLE_INTERFACE_H
#define CNUTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "cnuTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _cnuTable_initialize_interface(cnuTable_registration * user_ctx,
                                    u_long flags);
void _cnuTable_shutdown_interface(cnuTable_registration * user_ctx);

cnuTable_registration *
cnuTable_registration_get( void );

cnuTable_registration *
cnuTable_registration_set( cnuTable_registration * newreg );

netsnmp_container *cnuTable_container_get( void );
int cnuTable_container_size( void );

u_int cnuTable_dirty_get( void );
void cnuTable_dirty_set( u_int status );

    cnuTable_rowreq_ctx * cnuTable_allocate_rowreq_ctx(void *);
void cnuTable_release_rowreq_ctx(cnuTable_rowreq_ctx *rowreq_ctx);

int cnuTable_index_to_oid(netsnmp_index *oid_idx,
                            cnuTable_mib_index *mib_idx);
int cnuTable_index_from_oid(netsnmp_index *oid_idx,
                              cnuTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void cnuTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CNUTABLE_INTERFACE_H */
/** @} */
