/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cnuTable.h"
#include <snmp2cmm.h>


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cnuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cnuTable is subid 1 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.1, length: 9
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * cnuTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * cnuTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cnuTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
cnuTable_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cnuTable:cnuTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup cnuTable undo.
     * set up cnuTable undo information, in preparation for a set.
     * Undo storage is in (* cnuRowStatus_val_ptr )*
     */

    return rc;
} /* cnuTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cnuTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
cnuTable_undo( cnuTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cnuTable:cnuTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> cnuTable undo.
     * cnuTable undo information, in response to a failed set.
     * Undo storage is in (* cnuRowStatus_val_ptr )*
     */

    return rc;
} /* cnuTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cnuTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
cnuTable_undo_cleanup( cnuTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cnuTable:cnuTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup cnuTable undo.
     * Undo storage is in (* cnuRowStatus_val_ptr )*
     */

    return rc;
} /* cnuTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cnuTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param cnuTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int cnuTable_commit( cnuTable_rowreq_ctx *rowreq_ctx)
{
	int rc = MFD_SUCCESS;
	int             save_flags;

	DEBUGMSGTL(("verbose:cnuTable:cnuTable_commit","called\n"));

	/** we should have a non-NULL pointer */
	netsnmp_assert( NULL != rowreq_ctx );

	/*
	* save flags, then clear until we actually do something
	*/
	save_flags = rowreq_ctx->column_set_flags;
	rowreq_ctx->column_set_flags = 0;

	/*
	* commit cnuTable data
	* 1) check the column's flag in save_flags to see if it was set.
	* 2) clear the flag when you handle that column
	* 3) set the column's flag in column_set_flags if it needs undo
	*    processing in case of a failure.
	*/
	if (save_flags & COLUMN_CNUACTION_FLAG)
	{
		save_flags &= ~COLUMN_CNUACTION_FLAG; /* clear cnuAction */
		/*
		* TODO:482:o: |-> commit column cnuAction.
		*/
		/* modified by frank */
		if( 0 == rowreq_ctx->data.cnuRowStatus )
		{
			rc = 0;
		}
		else
		{
			//printf("-->cnu %d nodeAction = %d\n", rowreq_ctx->data.cnuIndex, rowreq_ctx->data.cnuAction);
			switch( rowreq_ctx->data.cnuAction )
			{
				case CNURSTACTVALUE_CNU_NO_ACTION:
				{
					rc = 0;
					break;
				}
				case CNURSTACTVALUE_CNU_RESET:
				{
					rc = snmp2cmm_resetCnu(rowreq_ctx->data.cnuIndex);
					break;
				}
				case CNURSTACTVALUE_CNU_RELOAD_PROFILE:
				{
					rc = snmp2cmm_reloadCnuProfile(rowreq_ctx->data.cnuIndex);
					break;
				}
				case CNURSTACTVALUE_CNU_PERMIT:
				{
					rc = snmp2cmm_permitCnu(rowreq_ctx->data.cnuIndex);
					break;
				}
				case CNURSTACTVALUE_CNU_UNDO_PERMIT:
				{
					rc = snmp2cmm_UndoPermitCnu(rowreq_ctx->data.cnuIndex);
					break;
				}
				case CNURSTACTVALUE_CNU_DIAGNOSE:
				{
					rc = 0;
					break;
				}
				case CNURSTACTVALUE_CNU_DELETE:
				{
					rc = snmp2cmm_DeleteCnu(rowreq_ctx->data.cnuIndex);
					break;
				}
				default:
				{
					rc = -1;
					break;
				}
			}
		}
		
		if( CMM_SUCCESS == rc )
		{
			/*
			* set flag, in case we need to undo cnuAction
			*/
			rowreq_ctx->column_set_flags |= COLUMN_CNUACTION_FLAG;
		}
		else
		{
			snmp_log(LOG_ERR,"cnuTable column cnuAction commit failed\n");
		}
	}

	/*
	* if we successfully commited this row, set the dirty flag.
	*/
	if (MFD_SUCCESS == rc)
	{
		rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
	}

	if (save_flags)
	{
		snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
		return MFD_ERROR;
	}

	return rc;
} /* cnuTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cnuTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param cnuTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
cnuTable_undo_commit( cnuTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cnuTable:cnuTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo cnuTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* cnuTable_undo_commit */

/*
 * TODO:440:M: Implement cnuTable node value checks.
 * TODO:450:M: Implement cnuTable undo functions.
 * TODO:460:M: Implement cnuTable set functions.
 * TODO:480:M: Implement cnuTable commit functions.
 */
/*---------------------------------------------------------------------
 * prevail-mib::cnuEntry.cnuAction
 * cnuAction is subid 13 of cnuEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.1.1.13
 * Description:
reset or force re-registation the CNU in EoC topology
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  cnu_no_action(0), cnu_reset(1), cnu_reload_profile(2), cnu_permit(3), cnu_undo_permit(4), cnu_diagnose(5), cnu_delete(6)
 *
 * Its syntax is CnuRstActValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cnuAction_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * cnuTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  cnu_no_action(0), cnu_reset(1), cnu_reload_profile(2), cnu_permit(3), cnu_undo_permit(4), cnu_diagnose(5), cnu_delete(6)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
cnuAction_check_value( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAction_val)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuAction_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid cnuAction value.
     */

    return MFD_SUCCESS; /* cnuAction value not illegal */
} /* cnuAction_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cnuTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * cnuTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
cnuAction_undo_setup( cnuTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuAction_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup cnuAction undo.
     */
    /*
     * copy cnuAction data
     * set rowreq_ctx->undo->cnuAction from rowreq_ctx->data.cnuAction
     */
    rowreq_ctx->undo->cnuAction = rowreq_ctx->data.cnuAction;


    return MFD_SUCCESS;
} /* cnuAction_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param cnuAction_val
 *        A long containing the new value.
 */
int
cnuAction_set( cnuTable_rowreq_ctx *rowreq_ctx, u_long cnuAction_val )
{

    DEBUGMSGTL(("verbose:cnuTable:cnuAction_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set cnuAction value.
     * set cnuAction value in rowreq_ctx->data
     */
    rowreq_ctx->data.cnuAction = cnuAction_val;

    return MFD_SUCCESS;
} /* cnuAction_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
cnuAction_undo( cnuTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:cnuTable:cnuAction_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up cnuAction undo.
     */
    /*
     * copy cnuAction data
     * set rowreq_ctx->data.cnuAction from rowreq_ctx->undo->cnuAction
     */
    rowreq_ctx->data.cnuAction = rowreq_ctx->undo->cnuAction;

    
    return MFD_SUCCESS;
} /* cnuAction_undo */

/**
 * check dependencies
 *
 * This is useful for for tables which have dependencies between columns
 * (or rows, or tables). For example, two columns allocating a percentage
 * of something add up 100%.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cnuTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @retval MFD_SUCCESS all the changes to the row are legal
 * @retval MFD_ERROR   one or more changes are not legal
 *
 * (see README-table-cnuTable if you don't have dependencies)
 */
int
cnuTable_check_dependencies(cnuTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:cnuTable_check_dependencies","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:470:o: Check cnuTable row dependencies.
     * check that all new value are legal and consistent with each other
     */
    return rc;
} /* cnuTable_check_dependencies */

/** @} */
