/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 17337 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for cnuTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cnuTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "cnuTable_interface.h"

const oid cnuTable_oid[] = { CNUTABLE_OID };
const int cnuTable_oid_size = OID_LENGTH(cnuTable_oid);

    cnuTable_registration  cnuTable_user_context;

void initialize_table_cnuTable(void);
void shutdown_table_cnuTable(void);


/**
 * Initializes the cnuTable module
 */
void
init_cnuTable(void)
{
    DEBUGMSGTL(("verbose:cnuTable:init_cnuTable","called\n"));

    /*
     * TODO:300:o: Perform cnuTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("cnuTable"))
        initialize_table_cnuTable();

} /* init_cnuTable */

/**
 * Shut-down the cnuTable module (agent is exiting)
 */
void
shutdown_cnuTable(void)
{
    if (should_init("cnuTable"))
        shutdown_table_cnuTable();

}

/**
 * Initialize the table cnuTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_cnuTable(void)
{
    cnuTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:cnuTable:initialize_table_cnuTable","called\n"));

    /*
     * TODO:301:o: Perform cnuTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize cnuTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("cnuTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _cnuTable_initialize_interface(user_context, flags);
} /* initialize_table_cnuTable */

/**
 * Shutdown the table cnuTable 
 */
void
shutdown_table_cnuTable(void)
{
    /*
     * call interface shutdown code
     */
    _cnuTable_shutdown_interface(&cnuTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
cnuTable_rowreq_ctx_init(cnuTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra cnuTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* cnuTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void cnuTable_rowreq_ctx_cleanup(cnuTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra cnuTable rowreq cleanup.
     */
} /* cnuTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
cnuTable_pre_request(cnuTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform cnuTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* cnuTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
cnuTable_post_request(cnuTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform cnuTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (cnuTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
        }
        
        cnuTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* cnuTable_post_request */


/** @{ */
