/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cnuTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "cnuTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table cnuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cnuTable is subid 1 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.1, length: 9
*/
typedef struct cnuTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache;

   cnuTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} cnuTable_interface_ctx;

static cnuTable_interface_ctx cnuTable_if_ctx;

static void _cnuTable_container_init(
    cnuTable_interface_ctx *if_ctx);
static void _cnuTable_container_shutdown(
    cnuTable_interface_ctx *if_ctx);


netsnmp_container *
cnuTable_container_get( void )
{
    return cnuTable_if_ctx.container;
}

cnuTable_registration *
cnuTable_registration_get( void )
{
    return cnuTable_if_ctx.user_ctx;
}

cnuTable_registration *
cnuTable_registration_set( cnuTable_registration * newreg )
{
    cnuTable_registration * old = cnuTable_if_ctx.user_ctx;
    cnuTable_if_ctx.user_ctx = newreg;
    return old;
}

int
cnuTable_container_size( void )
{
    return CONTAINER_SIZE(cnuTable_if_ctx.container);
}

u_int
cnuTable_dirty_get( void )
{
    return cnuTable_if_ctx.table_dirty;
}

void
cnuTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("cnuTable:cnuTable_dirty_set",
                "called. was %d, now %d\n",
                cnuTable_if_ctx.table_dirty, status));
    cnuTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_cnuTable_pre_request;
static Netsnmp_Node_Handler _mfd_cnuTable_post_request;
static Netsnmp_Node_Handler _mfd_cnuTable_object_lookup;
static Netsnmp_Node_Handler _mfd_cnuTable_get_values;
static Netsnmp_Node_Handler _mfd_cnuTable_check_objects;
static Netsnmp_Node_Handler _mfd_cnuTable_undo_setup;
static Netsnmp_Node_Handler _mfd_cnuTable_set_values;
static Netsnmp_Node_Handler _mfd_cnuTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_cnuTable_undo_values;
static Netsnmp_Node_Handler _mfd_cnuTable_commit;
static Netsnmp_Node_Handler _mfd_cnuTable_undo_commit;
static Netsnmp_Node_Handler _mfd_cnuTable_irreversible_commit;
static Netsnmp_Node_Handler _mfd_cnuTable_check_dependencies;

cnuTable_data *cnuTable_allocate_data(void);

/**
 * @internal
 * Initialize the table cnuTable 
 *    (Define its contents and how it's structured)
 */
void
_cnuTable_initialize_interface(cnuTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &cnuTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &cnuTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:cnuTable:_cnuTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for cnuTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: cnuTid */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrival. */
    tbl_info->min_column = CNUTABLE_MIN_COL;
    tbl_info->max_column = CNUTABLE_MAX_COL;

    /*
     * save users context
     */
    cnuTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    cnuTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _cnuTable_container_init(&cnuTable_if_ctx);
    if (NULL == cnuTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for cnuTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_cnuTable_object_lookup;
    access_multiplexer->get_values = _mfd_cnuTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_cnuTable_pre_request;
    access_multiplexer->post_request = _mfd_cnuTable_post_request;


    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_cnuTable_check_objects;
    access_multiplexer->undo_setup = _mfd_cnuTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_cnuTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_cnuTable_set_values;
    access_multiplexer->undo_sets = _mfd_cnuTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_cnuTable_commit;
    access_multiplexer->undo_commit = _mfd_cnuTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_cnuTable_irreversible_commit;
    
    /*
     * REQUIRED for tables with dependencies
     */
    access_multiplexer->consistency_checks = _mfd_cnuTable_check_dependencies;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("cnuTable:init_cnuTable",
                "Registering cnuTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("cnuTable", handler,
                                                  cnuTable_oid,
                                                  cnuTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
                                                  HANDLER_CAN_RWRITE
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table cnuTable\n");
        return;
    }
    reginfo->my_reg_void = &cnuTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            cnuTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != cnuTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(cnuTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _cnuTable_initialize_interface */

/**
 * @internal
 * Shutdown the table cnuTable
 */
void
_cnuTable_shutdown_interface(cnuTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _cnuTable_container_shutdown(&cnuTable_if_ctx);
}

void
cnuTable_valid_columns_set(netsnmp_column_info *vc)
{
    cnuTable_if_ctx.tbl_info.valid_columns = vc;
} /* cnuTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
cnuTable_index_to_oid(netsnmp_index *oid_idx,
                         cnuTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * cnuTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
     */
    netsnmp_variable_list var_cnuTid;

    /*
     * set up varbinds
     */
    memset( &var_cnuTid, 0x00, sizeof(var_cnuTid) );
    var_cnuTid.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_cnuTid.next_variable =  NULL;


    DEBUGMSGTL(("verbose:cnuTable:cnuTable_index_to_oid","called\n"));

        /* cnuTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    snmp_set_var_value(&var_cnuTid, (u_char*)&mib_idx->cnuTid,
                       sizeof(mib_idx->cnuTid));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_cnuTid);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_cnuTid );

    return err;
} /* cnuTable_index_to_oid */

/**
 * extract cnuTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
cnuTable_index_from_oid(netsnmp_index *oid_idx,
                         cnuTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * cnuTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
     */
    netsnmp_variable_list var_cnuTid;

    /*
     * set up varbinds
     */
    memset( &var_cnuTid, 0x00, sizeof(var_cnuTid) );
    var_cnuTid.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_cnuTid.next_variable =  NULL;


    DEBUGMSGTL(("verbose:cnuTable:cnuTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_cnuTid );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->cnuTid = *((long *)var_cnuTid.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_cnuTid );

    return err;
} /* cnuTable_index_from_oid */


/*
 * cnuTable_allocate_data
 *
 * Purpose: create new cnuTable_data.
 */
cnuTable_data *
cnuTable_allocate_data(void)
{
    cnuTable_data *rtn = SNMP_MALLOC_TYPEDEF(cnuTable_data);

    DEBUGMSGTL(("verbose:cnuTable:cnuTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "cnuTable_data.\n");
    }

    return rtn;
} /* cnuTable_allocate_data */

/*
 * cnuTable_release_data
 *
 * Purpose: release cnuTable data.
 */
void
cnuTable_release_data(cnuTable_data *data)
{
    DEBUGMSGTL(("verbose:cnuTable:cnuTable_release_data","called\n"));

    free(data);
} /* cnuTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a cnuTable_rowreq_ctx
 */
cnuTable_rowreq_ctx *
cnuTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(cnuTable_rowreq_ctx);

    DEBUGMSGTL(("internal:cnuTable:cnuTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "cnuTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->cnuTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            cnuTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           cnuTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* cnuTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a cnuTable_rowreq_ctx
 */
void
cnuTable_release_rowreq_ctx(cnuTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:cnuTable:cnuTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    cnuTable_rowreq_ctx_cleanup(rowreq_ctx);

    if(rowreq_ctx->undo)
        cnuTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* cnuTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_cnuTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:cnuTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = cnuTable_pre_request(cnuTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("cnuTable","error %d from "
                    "cnuTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_cnuTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        cnuTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:cnuTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && cnuTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "cnuTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = cnuTable_post_request(cnuTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("cnuTable","error %d from "
                    "cnuTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_cnuTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * cnuTable_interface_ctx *if_ctx =
     *             (cnuTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        cnuTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_cnuTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_cnuTable_get_column( cnuTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* (INDEX) cnuTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    case COLUMN_CNUTID:
    var->type = ASN_INTEGER;
        var->val_len = sizeof(long);
        (*var->val.integer) = rowreq_ctx->tbl_idx.cnuTid;
        break;

    /* cnuIndex(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    case COLUMN_CNUINDEX:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = cnuIndex_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* cnuModel(3)/DevModelValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUMODEL:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuModel_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* cnuMacAddress(4)/MacAddress/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUMACADDRESS:
    var->type = ASN_OCTET_STR;
rc = cnuMacAddress_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* cnuOnlineStatus(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUONLINESTATUS:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuOnlineStatus_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* cnuAuthorized(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUAUTHORIZED:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuAuthorized_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* cnuSoftwareVersion(7)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUSOFTWAREVERSION:
    var->type = ASN_OCTET_STR;
rc = cnuSoftwareVersion_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* cnuRxRate(8)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_CNURXRATE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = cnuRxRate_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* cnuTxRate(9)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_CNUTXRATE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = cnuTxRate_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* cnuSnr(10)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUSNR:
    var->type = ASN_OCTET_STR;
rc = cnuSnr_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* cnuBpc(11)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUBPC:
    var->type = ASN_OCTET_STR;
rc = cnuBpc_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* cnuAttenuation(12)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUATTENUATION:
    var->type = ASN_OCTET_STR;
rc = cnuAttenuation_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* cnuAction(13)/CnuRstActValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_CNUACTION:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuAction_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* cnuSynchronized(14)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUSYNCHRONIZED:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuSynchronized_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* cnuRowStatus(15)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUROWSTATUS:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = cnuRowStatus_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (CNUTABLE_MIN_COL <= column && column <= CNUTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _cnuTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _cnuTable_get_column */

int
_mfd_cnuTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _cnuTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_cnuTable_check_column( cnuTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {
    /* (INDEX) cnuTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    case COLUMN_CNUTID:
        rc = SNMP_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /* cnuIndex(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    case COLUMN_CNUINDEX:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuModel(3)/DevModelValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUMODEL:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuMacAddress(4)/MacAddress/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUMACADDRESS:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuOnlineStatus(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUONLINESTATUS:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuAuthorized(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUAUTHORIZED:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuSoftwareVersion(7)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUSOFTWAREVERSION:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuRxRate(8)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_CNURXRATE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuTxRate(9)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_CNUTXRATE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuSnr(10)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUSNR:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuBpc(11)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUBPC:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuAttenuation(12)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_CNUATTENUATION:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuAction(13)/CnuRstActValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_CNUACTION:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.cnuAction ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != CNURSTACTVALUE_CNU_NO_ACTION )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_RESET )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_RELOAD_PROFILE )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_PERMIT )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_UNDO_PERMIT )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_DIAGNOSE )
 && ( *var->val.integer != CNURSTACTVALUE_CNU_DELETE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("cnuTable:_cnuTable_check_column:cnuAction",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = cnuAction_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from cnuAction_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* cnuSynchronized(14)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUSYNCHRONIZED:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* cnuRowStatus(15)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CNUROWSTATUS:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _cnuTable_check_column\n", column);
    }

    return rc;
} /* _cnuTable_check_column */

int
_mfd_cnuTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _cnuTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: check dependencies
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check dependencies wrapper
 */
static int
_mfd_cnuTable_check_dependencies(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_check_dependencies","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rc = cnuTable_check_dependencies(rowreq_ctx);
    if(rc){
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_check_dependencies\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_check_dependencies */

/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_cnuTable_undo_setup_column( cnuTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* cnuAction(13)/CnuRstActValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_CNUACTION:
        rowreq_ctx->column_set_flags |= COLUMN_CNUACTION_FLAG;
        rc = cnuAction_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _cnuTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _cnuTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_cnuTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = cnuTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = cnuTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _cnuTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("cnuTable:mfd","error %d from "
                            "cnuTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_cnuTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = cnuTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         cnuTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_cnuTable_set_column( cnuTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* cnuAction(13)/CnuRstActValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_CNUACTION:
        rowreq_ctx->column_set_flags |= COLUMN_CNUACTION_FLAG;
        rc = cnuAction_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _cnuTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _cnuTable_set_column */

int
_mfd_cnuTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _cnuTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("cnuTable:mfd","error %d from "
                        "cnuTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_cnuTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = cnuTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        cnuTable_dirty_set( cnuTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_cnuTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = cnuTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            cnuTable_dirty_set( d - 1 );
    }

    rc = cnuTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "cnuTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_cnuTable_undo_column( cnuTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* cnuAction(13)/CnuRstActValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_CNUACTION:
        rc = cnuAction_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _cnuTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _cnuTable_undo_column */

int
_mfd_cnuTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = cnuTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("cnuTable:mfd","error %d from "
                    "cnuTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _cnuTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("cnuTable:mfd","error %d from "
                        "cnuTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_cnuTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    cnuTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:cnuTable:_mfd_cnuTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(cnuTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_cnuTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free(netsnmp_container *container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:cnuTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for cnuTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return cnuTable_container_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cnuTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in cnuTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    _container_free(container);
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(cnuTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:cnuTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    cnuTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:cnuTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in cnuTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    cnuTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_cnuTable_container_init(cnuTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_container_init","called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         cnuTable_oid,
                                         cnuTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for cnuTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    cnuTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("cnuTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "cnuTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void*)if_ctx->container;
} /* _cnuTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_cnuTable_container_shutdown(cnuTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:cnuTable:_cnuTable_container_shutdown","called\n"));

    cnuTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _cnuTable_container_shutdown */


cnuTable_rowreq_ctx *
cnuTable_row_find_by_mib_index(cnuTable_mib_index *mib_idx)
{
    cnuTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = cnuTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = CONTAINER_FIND(cnuTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

