/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef CNUTABLE_DATA_ACCESS_H
#define CNUTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cnuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cnuTable is subid 1 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.1, length: 9
*/


    int cnuTable_init_data(cnuTable_registration * cnuTable_reg);


    /*
     * TODO:180:o: Review cnuTable cache timeout.
     * The number of seconds before the cache times out
     */
#define CNUTABLE_CACHE_TIMEOUT   60

void cnuTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void cnuTable_container_shutdown(netsnmp_container *container_ptr);

int cnuTable_container_load(netsnmp_container *container);
void cnuTable_container_free(netsnmp_container *container);

int cnuTable_cache_load(netsnmp_container *container);
void cnuTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int cnuTable_row_prep( cnuTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* CNUTABLE_DATA_ACCESS_H */
