/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("cnuTable")) shutdown_cnuTable();
  if (should_init("profileTable")) shutdown_profileTable();
  if (should_init("cltTable")) shutdown_cltTable();
  if (should_init("cltproTable")) shutdown_cltproTable();
  if (should_init("ifTable")) shutdown_ifTable();
  if (should_init("ifXTable")) shutdown_ifXTable();
  if (should_init("cpu")) shutdown_cpu();
