/* This file is automatically generated by configure.  Do not modify by hand. */
/* Define if compiling with the ucd-snmp/dlmod module files.  */
#define USING_UCD_SNMP_DLMOD_MODULE 1
 
/* Define if compiling with the if-mib module files.  */
#define USING_IF_MIB_MODULE 1
 
/* Define if compiling with the host module files.  */
#define USING_HOST_MODULE 1
 
/* Define if compiling with the mibII/system_mib module files.  */
#define USING_MIBII_SYSTEM_MIB_MODULE 1
 
/* Define if compiling with the mibII/sysORTable module files.  */
#define USING_MIBII_SYSORTABLE_MODULE 1
 
/* Define if compiling with the mibII/at module files.  */
#define USING_MIBII_AT_MODULE 1
 
/* Define if compiling with the mibII/ifTable module files.  */
#define USING_MIBII_IFTABLE_MODULE 1
 
/* Define if compiling with the mibII/ip module files.  */
#define USING_MIBII_IP_MODULE 1
 
/* Define if compiling with the mibII/snmp_mib module files.  */
#define USING_MIBII_SNMP_MIB_MODULE 1
 
/* Define if compiling with the mibII/tcp module files.  */
#define USING_MIBII_TCP_MODULE 1
 
/* Define if compiling with the mibII/icmp module files.  */
#define USING_MIBII_ICMP_MODULE 1
 
/* Define if compiling with the mibII/udp module files.  */
#define USING_MIBII_UDP_MODULE 1
 
/* Define if compiling with the prevail-mib/cbatAction/cbatAction module files.  */
#define USING_PREVAIL_MIB_CBATACTION_CBATACTION_MODULE 1
 
/* Define if compiling with the prevail-mib/softwareMgmt/softwareMgmt module files.  */
#define USING_PREVAIL_MIB_SOFTWAREMGMT_SOFTWAREMGMT_MODULE 1
 
/* Define if compiling with the prevail-mib/networkInfo/networkInfo module files.  */
#define USING_PREVAIL_MIB_NETWORKINFO_NETWORKINFO_MODULE 1
 
/* Define if compiling with the prevail-mib/snmpGroup/snmpGroup module files.  */
#define USING_PREVAIL_MIB_SNMPGROUP_SNMPGROUP_MODULE 1
 
/* Define if compiling with the prevail-mib/systemDesc/systemDesc module files.  */
#define USING_PREVAIL_MIB_SYSTEMDESC_SYSTEMDESC_MODULE 1
 
/* Define if compiling with the prevail-mib/systemInfo/systemInfo module files.  */
#define USING_PREVAIL_MIB_SYSTEMINFO_SYSTEMINFO_MODULE 1
 
/* Define if compiling with the prevail-mib/cnuTable/cnuTable module files.  */
#define USING_PREVAIL_MIB_CNUTABLE_CNUTABLE_MODULE 1
 
/* Define if compiling with the prevail-mib/profileTable/profileTable module files.  */
#define USING_PREVAIL_MIB_PROFILETABLE_PROFILETABLE_MODULE 1
 
/* Define if compiling with the prevail-mib/cltTable/cltTable module files.  */
#define USING_PREVAIL_MIB_CLTTABLE_CLTTABLE_MODULE 1
 
/* Define if compiling with the prevail-mib/cltproTable/cltproTable module files.  */
#define USING_PREVAIL_MIB_CLTPROTABLE_CLTPROTABLE_MODULE 1
 
/* Define if compiling with the default_modules module files.  */
#define USING_DEFAULT_MODULES_MODULE 1
 
/* Define if compiling with the if-mib/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable module files.  */
#define USING_IF_MIB_IFXTABLE_MODULE 1
 
/* Define if compiling with the host/hr_system module files.  */
#define USING_HOST_HR_SYSTEM_MODULE 1
 
/* Define if compiling with the host/hr_storage module files.  */
#define USING_HOST_HR_STORAGE_MODULE 1
 
/* Define if compiling with the host/hr_device module files.  */
#define USING_HOST_HR_DEVICE_MODULE 1
 
/* Define if compiling with the host/hr_other module files.  */
#define USING_HOST_HR_OTHER_MODULE 1
 
/* Define if compiling with the host/hr_proc module files.  */
#define USING_HOST_HR_PROC_MODULE 1
 
/* Define if compiling with the host/hr_network module files.  */
#define USING_HOST_HR_NETWORK_MODULE 1
 
/* Define if compiling with the host/hr_print module files.  */
#define USING_HOST_HR_PRINT_MODULE 1
 
/* Define if compiling with the host/hr_disk module files.  */
#define USING_HOST_HR_DISK_MODULE 1
 
/* Define if compiling with the host/hr_partition module files.  */
#define USING_HOST_HR_PARTITION_MODULE 1
 
/* Define if compiling with the host/hr_filesys module files.  */
#define USING_HOST_HR_FILESYS_MODULE 1
 
/* Define if compiling with the host/hr_swrun module files.  */
#define USING_HOST_HR_SWRUN_MODULE 1
 
/* Define if compiling with the host/hr_swinst module files.  */
#define USING_HOST_HR_SWINST_MODULE 1
 
/* Define if compiling with the util_funcs module files.  */
#define USING_UTIL_FUNCS_MODULE 1
 
/* Define if compiling with the mibII/kernel_linux module files.  */
#define USING_MIBII_KERNEL_LINUX_MODULE 1
 
/* Define if compiling with the mibII/ipAddr module files.  */
#define USING_MIBII_IPADDR_MODULE 1
 
/* Define if compiling with the mibII/var_route module files.  */
#define USING_MIBII_VAR_ROUTE_MODULE 1
 
/* Define if compiling with the mibII/route_write module files.  */
#define USING_MIBII_ROUTE_WRITE_MODULE 1
 
/* Define if compiling with the mibII/tcpTable module files.  */
#define USING_MIBII_TCPTABLE_MODULE 1
 
/* Define if compiling with the mibII/udpTable module files.  */
#define USING_MIBII_UDPTABLE_MODULE 1
 
/* Define if compiling with the prevail-mib/cnuTable/cnuTable_interface module files.  */
#define USING_PREVAIL_MIB_CNUTABLE_CNUTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the prevail-mib/cnuTable/cnuTable_data_access module files.  */
#define USING_PREVAIL_MIB_CNUTABLE_CNUTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the prevail-mib/cnuTable/cnuTable_data_get module files.  */
#define USING_PREVAIL_MIB_CNUTABLE_CNUTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the prevail-mib/cnuTable/cnuTable_data_set module files.  */
#define USING_PREVAIL_MIB_CNUTABLE_CNUTABLE_DATA_SET_MODULE 1
 
/* Define if compiling with the prevail-mib/profileTable/profileTable_interface module files.  */
#define USING_PREVAIL_MIB_PROFILETABLE_PROFILETABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the prevail-mib/profileTable/profileTable_data_access module files.  */
#define USING_PREVAIL_MIB_PROFILETABLE_PROFILETABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the prevail-mib/profileTable/profileTable_data_get module files.  */
#define USING_PREVAIL_MIB_PROFILETABLE_PROFILETABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the prevail-mib/profileTable/profileTable_data_set module files.  */
#define USING_PREVAIL_MIB_PROFILETABLE_PROFILETABLE_DATA_SET_MODULE 1
 
/* Define if compiling with the prevail-mib/cltTable/cltTable_interface module files.  */
#define USING_PREVAIL_MIB_CLTTABLE_CLTTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the prevail-mib/cltTable/cltTable_data_access module files.  */
#define USING_PREVAIL_MIB_CLTTABLE_CLTTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the prevail-mib/cltTable/cltTable_data_get module files.  */
#define USING_PREVAIL_MIB_CLTTABLE_CLTTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the prevail-mib/cltTable/cltTable_data_set module files.  */
#define USING_PREVAIL_MIB_CLTTABLE_CLTTABLE_DATA_SET_MODULE 1
 
/* Define if compiling with the prevail-mib/cltproTable/cltproTable_interface module files.  */
#define USING_PREVAIL_MIB_CLTPROTABLE_CLTPROTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the prevail-mib/cltproTable/cltproTable_data_access module files.  */
#define USING_PREVAIL_MIB_CLTPROTABLE_CLTPROTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the prevail-mib/cltproTable/cltproTable_data_get module files.  */
#define USING_PREVAIL_MIB_CLTPROTABLE_CLTPROTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the prevail-mib/cltproTable/cltproTable_data_set module files.  */
#define USING_PREVAIL_MIB_CLTPROTABLE_CLTPROTABLE_DATA_SET_MODULE 1
 
/* Define if compiling with the mibII/vacm_vars module files.  */
#define USING_MIBII_VACM_VARS_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_MODULE 1
 
/* Define if compiling with the hardware/memory module files.  */
#define USING_HARDWARE_MEMORY_MODULE 1
 
/* Define if compiling with the hardware/cpu module files.  */
#define USING_HARDWARE_CPU_MODULE 1
 
/* Define if compiling with the mibII/vacm_context module files.  */
#define USING_MIBII_VACM_CONTEXT_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_interface module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_data_access module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable_interface module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable_data_access module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the hardware/memory/hw_mem module files.  */
#define USING_HARDWARE_MEMORY_HW_MEM_MODULE 1
 
/* Define if compiling with the hardware/memory/memory_linux module files.  */
#define USING_HARDWARE_MEMORY_MEMORY_LINUX_MODULE 1
 
/* Define if compiling with the hardware/cpu/cpu module files.  */
#define USING_HARDWARE_CPU_CPU_MODULE 1
 
/* Define if compiling with the hardware/cpu/cpu_linux module files.  */
#define USING_HARDWARE_CPU_CPU_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_linux module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_ioctl module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_IOCTL_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_ioctl module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_IOCTL_MODULE 1
 
