/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file cltTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CLTTABLE_DATA_GET_H
#define CLTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cltTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cltTable is subid 9 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.9, length: 9
*/
    /*
     * indexes
     */

    int cltIndex_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltIndex_val_ptr );
    int cltModel_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltModel_val_ptr );
    int cltMacAddress_get( cltTable_rowreq_ctx *rowreq_ctx, char **cltMacAddress_val_ptr_ptr, size_t *cltMacAddress_val_ptr_len_ptr );
    int cltOnlineStatus_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltOnlineStatus_val_ptr );
    int cltMaxStats_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltMaxStats_val_ptr );
    int cltNumStats_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltNumStats_val_ptr );
    int cltSoftwareVersion_get( cltTable_rowreq_ctx *rowreq_ctx, char **cltSoftwareVersion_val_ptr_ptr, size_t *cltSoftwareVersion_val_ptr_len_ptr );
    int cltSynchronized_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltSynchronized_val_ptr );
    int cltAction_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltAction_val_ptr );
    int cltRowStatus_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltRowStatus_val_ptr );


int cltTable_indexes_set_tbl_idx(cltTable_mib_index *tbl_idx, long cltTid_val);
int cltTable_indexes_set(cltTable_rowreq_ctx *rowreq_ctx, long cltTid_val);




#ifdef __cplusplus
}
#endif

#endif /* CLTTABLE_DATA_GET_H */
/** @} */
