/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CLTTABLE_INTERFACE_H
#define CLTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "cltTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _cltTable_initialize_interface(cltTable_registration * user_ctx,
                                    u_long flags);
void _cltTable_shutdown_interface(cltTable_registration * user_ctx);

cltTable_registration *
cltTable_registration_get( void );

cltTable_registration *
cltTable_registration_set( cltTable_registration * newreg );

netsnmp_container *cltTable_container_get( void );
int cltTable_container_size( void );

u_int cltTable_dirty_get( void );
void cltTable_dirty_set( u_int status );

    cltTable_rowreq_ctx * cltTable_allocate_rowreq_ctx(void *);
void cltTable_release_rowreq_ctx(cltTable_rowreq_ctx *rowreq_ctx);

int cltTable_index_to_oid(netsnmp_index *oid_idx,
                            cltTable_mib_index *mib_idx);
int cltTable_index_from_oid(netsnmp_index *oid_idx,
                              cltTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void cltTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CLTTABLE_INTERFACE_H */
/** @} */
