/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef CLTTABLE_DATA_SET_H
#define CLTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cltTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cltTable is subid 9 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.9, length: 9
*/


int cltTable_undo_setup( cltTable_rowreq_ctx *rowreq_ctx);
int cltTable_undo_cleanup( cltTable_rowreq_ctx *rowreq_ctx);
int cltTable_undo( cltTable_rowreq_ctx *rowreq_ctx);
int cltTable_commit( cltTable_rowreq_ctx *rowreq_ctx);
int cltTable_undo_commit( cltTable_rowreq_ctx *rowreq_ctx);


int cltIndex_check_value( cltTable_rowreq_ctx *rowreq_ctx, long cltIndex_val);
int cltIndex_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltIndex_set( cltTable_rowreq_ctx *rowreq_ctx, long cltIndex_val );
int cltIndex_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltModel_check_value( cltTable_rowreq_ctx *rowreq_ctx, u_long cltModel_val);
int cltModel_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltModel_set( cltTable_rowreq_ctx *rowreq_ctx, u_long cltModel_val );
int cltModel_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltMacAddress_check_value( cltTable_rowreq_ctx *rowreq_ctx, char *cltMacAddress_val_ptr,  size_t cltMacAddress_val_ptr_len);
int cltMacAddress_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltMacAddress_set( cltTable_rowreq_ctx *rowreq_ctx, char *cltMacAddress_val_ptr,  size_t cltMacAddress_val_ptr_len );
int cltMacAddress_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltOnlineStatus_check_value( cltTable_rowreq_ctx *rowreq_ctx, u_long cltOnlineStatus_val);
int cltOnlineStatus_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltOnlineStatus_set( cltTable_rowreq_ctx *rowreq_ctx, u_long cltOnlineStatus_val );
int cltOnlineStatus_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltMaxStats_check_value( cltTable_rowreq_ctx *rowreq_ctx, long cltMaxStats_val);
int cltMaxStats_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltMaxStats_set( cltTable_rowreq_ctx *rowreq_ctx, long cltMaxStats_val );
int cltMaxStats_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltNumStats_check_value( cltTable_rowreq_ctx *rowreq_ctx, long cltNumStats_val);
int cltNumStats_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltNumStats_set( cltTable_rowreq_ctx *rowreq_ctx, long cltNumStats_val );
int cltNumStats_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltSoftwareVersion_check_value( cltTable_rowreq_ctx *rowreq_ctx, char *cltSoftwareVersion_val_ptr,  size_t cltSoftwareVersion_val_ptr_len);
int cltSoftwareVersion_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltSoftwareVersion_set( cltTable_rowreq_ctx *rowreq_ctx, char *cltSoftwareVersion_val_ptr,  size_t cltSoftwareVersion_val_ptr_len );
int cltSoftwareVersion_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltSynchronized_check_value( cltTable_rowreq_ctx *rowreq_ctx, u_long cltSynchronized_val);
int cltSynchronized_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltSynchronized_set( cltTable_rowreq_ctx *rowreq_ctx, u_long cltSynchronized_val );
int cltSynchronized_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltAction_check_value( cltTable_rowreq_ctx *rowreq_ctx, u_long cltAction_val);
int cltAction_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltAction_set( cltTable_rowreq_ctx *rowreq_ctx, u_long cltAction_val );
int cltAction_undo( cltTable_rowreq_ctx *rowreq_ctx );

int cltRowStatus_check_value( cltTable_rowreq_ctx *rowreq_ctx, u_long cltRowStatus_val);
int cltRowStatus_undo_setup( cltTable_rowreq_ctx *rowreq_ctx );
int cltRowStatus_set( cltTable_rowreq_ctx *rowreq_ctx, u_long cltRowStatus_val );
int cltRowStatus_undo( cltTable_rowreq_ctx *rowreq_ctx );


int cltTable_check_dependencies(cltTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CLTTABLE_DATA_SET_H */
