/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cltTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement cltTable get routines.
 * TODO:240:M: Implement cltTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cltTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * prevail-mib::cltTable is subid 9 of modEoCMib.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.36186.8.9, length: 9
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement cltTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param cltTid_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
cltTable_indexes_set_tbl_idx(cltTable_mib_index *tbl_idx, long cltTid_val)
{
    DEBUGMSGTL(("verbose:cltTable:cltTable_indexes_set_tbl_idx","called\n"));

    /* cltTid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->cltTid = cltTid_val;
    

    return MFD_SUCCESS;
} /* cltTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
cltTable_indexes_set(cltTable_rowreq_ctx *rowreq_ctx, long cltTid_val)
{
    DEBUGMSGTL(("verbose:cltTable:cltTable_indexes_set","called\n"));

    if(MFD_SUCCESS != cltTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , cltTid_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != cltTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* cltTable_indexes_set */


/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltIndex
 * cltIndex is subid 2 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.2
 * Description:
the index of clt entry in databases.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 4;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltIndex data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltIndex_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltIndex_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltIndex_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltIndex_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltIndex_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltIndex data.
 * copy (* cltIndex_val_ptr ) from rowreq_ctx->data
 */
    (* cltIndex_val_ptr ) = rowreq_ctx->data.cltIndex;

    return MFD_SUCCESS;
} /* cltIndex_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltModel
 * cltModel is subid 3 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.3
 * Description:
the model of EoC products in prevail.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 9/16. Values:  X7(1), E31(2), Q31(3), C22(4), S220(5), S60(6), L2(7), L3(8), C2(9), C4(10), CLT1(11), UNKNOWN(256)
 *
 * Its syntax is DevModelValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltModel data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltModel_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltModel_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltModel_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltModel_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltModel_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltModel data.
 * copy (* cltModel_val_ptr ) from rowreq_ctx->data
 */
    (* cltModel_val_ptr ) = rowreq_ctx->data.cltModel;

    return MFD_SUCCESS;
} /* cltModel_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltMacAddress
 * cltMacAddress is subid 4 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.4
 * Description:
the mac address of clt.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 1x:
 *
 * Ranges:  6;
 *
 * Its syntax is MacAddress (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 6)
 */
/**
 * Extract the current value of the cltMacAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltMacAddress_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param cltMacAddress_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by cltMacAddress.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*cltMacAddress_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update cltMacAddress_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
cltMacAddress_get( cltTable_rowreq_ctx *rowreq_ctx, char **cltMacAddress_val_ptr_ptr, size_t *cltMacAddress_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != cltMacAddress_val_ptr_ptr) && (NULL != *cltMacAddress_val_ptr_ptr));
   netsnmp_assert( NULL != cltMacAddress_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltMacAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltMacAddress data.
 * copy (* cltMacAddress_val_ptr_ptr ) data and (* cltMacAddress_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for cltMacAddress data
     */
    if ((NULL == (* cltMacAddress_val_ptr_ptr )) ||
        ((* cltMacAddress_val_ptr_len_ptr ) <
         (rowreq_ctx->data.cltMacAddress_len* sizeof(rowreq_ctx->data.cltMacAddress[0])))) {
        /*
         * allocate space for cltMacAddress data
         */
        (* cltMacAddress_val_ptr_ptr ) = malloc(rowreq_ctx->data.cltMacAddress_len* sizeof(rowreq_ctx->data.cltMacAddress[0]));
        if(NULL == (* cltMacAddress_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* cltMacAddress_val_ptr_len_ptr ) = rowreq_ctx->data.cltMacAddress_len* sizeof(rowreq_ctx->data.cltMacAddress[0]);
    memcpy( (* cltMacAddress_val_ptr_ptr ), rowreq_ctx->data.cltMacAddress, rowreq_ctx->data.cltMacAddress_len* sizeof(rowreq_ctx->data.cltMacAddress[0]) );

    return MFD_SUCCESS;
} /* cltMacAddress_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltOnlineStatus
 * cltOnlineStatus is subid 5 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.5
 * Description:
The online status of clt in EoC topology
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltOnlineStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltOnlineStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltOnlineStatus_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltOnlineStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltOnlineStatus_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltOnlineStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltOnlineStatus data.
 * copy (* cltOnlineStatus_val_ptr ) from rowreq_ctx->data
 */
    (* cltOnlineStatus_val_ptr ) = rowreq_ctx->data.cltOnlineStatus;

    return MFD_SUCCESS;
} /* cltOnlineStatus_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltMaxStats
 * cltMaxStats is subid 6 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.6
 * Description:
the max cnus supported by clt.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 256;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltMaxStats data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltMaxStats_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltMaxStats_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltMaxStats_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltMaxStats_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltMaxStats_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltMaxStats data.
 * copy (* cltMaxStats_val_ptr ) from rowreq_ctx->data
 */
    (* cltMaxStats_val_ptr ) = rowreq_ctx->data.cltMaxStats;

    return MFD_SUCCESS;
} /* cltMaxStats_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltNumStats
 * cltNumStats is subid 7 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.7
 * Description:
the current cnus managed by clt.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 256;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the cltNumStats data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltNumStats_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltNumStats_get( cltTable_rowreq_ctx *rowreq_ctx, long * cltNumStats_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltNumStats_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltNumStats_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltNumStats data.
 * copy (* cltNumStats_val_ptr ) from rowreq_ctx->data
 */
    (* cltNumStats_val_ptr ) = rowreq_ctx->data.cltNumStats;

    return MFD_SUCCESS;
} /* cltNumStats_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltSoftwareVersion
 * cltSoftwareVersion is subid 8 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.8
 * Description:
the software version of the CNU.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the cltSoftwareVersion data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltSoftwareVersion_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param cltSoftwareVersion_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by cltSoftwareVersion.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*cltSoftwareVersion_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update cltSoftwareVersion_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
cltSoftwareVersion_get( cltTable_rowreq_ctx *rowreq_ctx, char **cltSoftwareVersion_val_ptr_ptr, size_t *cltSoftwareVersion_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != cltSoftwareVersion_val_ptr_ptr) && (NULL != *cltSoftwareVersion_val_ptr_ptr));
   netsnmp_assert( NULL != cltSoftwareVersion_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltSoftwareVersion_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltSoftwareVersion data.
 * copy (* cltSoftwareVersion_val_ptr_ptr ) data and (* cltSoftwareVersion_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for cltSoftwareVersion data
     */
    if ((NULL == (* cltSoftwareVersion_val_ptr_ptr )) ||
        ((* cltSoftwareVersion_val_ptr_len_ptr ) <
         (rowreq_ctx->data.cltSoftwareVersion_len* sizeof(rowreq_ctx->data.cltSoftwareVersion[0])))) {
        /*
         * allocate space for cltSoftwareVersion data
         */
        (* cltSoftwareVersion_val_ptr_ptr ) = malloc(rowreq_ctx->data.cltSoftwareVersion_len* sizeof(rowreq_ctx->data.cltSoftwareVersion[0]));
        if(NULL == (* cltSoftwareVersion_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* cltSoftwareVersion_val_ptr_len_ptr ) = rowreq_ctx->data.cltSoftwareVersion_len* sizeof(rowreq_ctx->data.cltSoftwareVersion[0]);
    memcpy( (* cltSoftwareVersion_val_ptr_ptr ), rowreq_ctx->data.cltSoftwareVersion, rowreq_ctx->data.cltSoftwareVersion_len* sizeof(rowreq_ctx->data.cltSoftwareVersion[0]) );

    return MFD_SUCCESS;
} /* cltSoftwareVersion_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltSynchronized
 * cltSynchronized is subid 9 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.9
 * Description:
The clt profile synchronization flag.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltSynchronized data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltSynchronized_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltSynchronized_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltSynchronized_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltSynchronized_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltSynchronized_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltSynchronized data.
 * copy (* cltSynchronized_val_ptr ) from rowreq_ctx->data
 */
    (* cltSynchronized_val_ptr ) = rowreq_ctx->data.cltSynchronized;

    return MFD_SUCCESS;
} /* cltSynchronized_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltAction
 * cltAction is subid 10 of cltEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.36186.8.9.1.10
 * Description:
reset or force re-registation the clt in EoC topology
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  clt_no_action(0), clt_reset(1), clt_reload_profile(2), clt_delete(3)
 *
 * Its syntax is CltNodeActValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltAction data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltAction_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltAction_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltAction_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltAction_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltAction_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltAction data.
 * copy (* cltAction_val_ptr ) from rowreq_ctx->data
 */
    (* cltAction_val_ptr ) = rowreq_ctx->data.cltAction;

    return MFD_SUCCESS;
} /* cltAction_get */

/*---------------------------------------------------------------------
 * prevail-mib::cltEntry.cltRowStatus
 * cltRowStatus is subid 11 of cltEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.36186.8.9.1.11
 * Description:
The node entry status of clt.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the cltRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cltRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
cltRowStatus_get( cltTable_rowreq_ctx *rowreq_ctx, u_long * cltRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != cltRowStatus_val_ptr );


    DEBUGMSGTL(("verbose:cltTable:cltRowStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cltRowStatus data.
 * copy (* cltRowStatus_val_ptr ) from rowreq_ctx->data
 */
    (* cltRowStatus_val_ptr ) = rowreq_ctx->data.cltRowStatus;

    return MFD_SUCCESS;
} /* cltRowStatus_get */



/** @} */
