/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 17548 2009-04-23 16:35:18Z hardaker $
 *
 * $Id:$
 */
#ifndef CLTTABLE_OIDS_H
#define CLTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table cltTable */
#define CLTTABLE_OID              1,3,6,1,4,1,36186,8,9


#define COLUMN_CLTTID         1
    
#define COLUMN_CLTINDEX         2
    
#define COLUMN_CLTMODEL         3
    
#define COLUMN_CLTMACADDRESS         4
    
#define COLUMN_CLTONLINESTATUS         5
    
#define COLUMN_CLTMAXSTATS         6
    
#define COLUMN_CLTNUMSTATS         7
    
#define COLUMN_CLTSOFTWAREVERSION         8
    
#define COLUMN_CLTSYNCHRONIZED         9
    
#define COLUMN_CLTACTION         10
#define COLUMN_CLTACTION_FLAG    (0x1 << 0)
    
#define COLUMN_CLTROWSTATUS         11
    

#define CLTTABLE_MIN_COL   COLUMN_CLTTID
#define CLTTABLE_MAX_COL   COLUMN_CLTROWSTATUS
    

    /*
     * TODO:405:r: Review CLTTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define CLTTABLE_SETTABLE_COLS (COLUMN_CLTACTION_FLAG)

#ifdef __cplusplus
}
#endif

#endif /* CLTTABLE_OIDS_H */
